image: docker:latest

services:
  - docker:dind

stages:
  - lint
  - build
  - test
  - deliver
  - deploy

snyk-check:
  stage: lint
  tags:
    - lint
  image:
    name: snyk/snyk-cli:docker
    entrypoint: [""]
  script:
    # - docker build -t app:$CI_COMMIT_SHORT_SHA .
    - snyk auth $SNYK_TOKEN
    - snyk test --all-projects --org=3eef733d-b6ce-4399-8f32-3691e465a4e1
    - snyk monitor --all-projects --org=3eef733d-b6ce-4399-8f32-3691e465a4e1
  allow_failure: true # set false to fail on vulnerabilities.
  only:
    - merge_requests
    - main


sonarqube-check:
  stage: lint
  tags:
    - lint
  image: 
    name: sonarsource/sonar-scanner-cli:5.0
    entrypoint: [""]
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
    GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script: 
    - sonar-scanner
  allow_failure: true # set false to fail on errors.
  only:
    - merge_requests
    - main





build_backend:
  stage: build
  tags:
    - build
  needs:
    - sonarqube-check
    - snyk-check
  script:
    - echo "build backend"
    - docker build -t cooopeir/conint:latest ./backend

build_blue:
  stage: build
  tags:
    - build
  needs:
    - sonarqube-check
    - snyk-check  
  script:
    - echo "build blue"
    - docker build -t cooopeir/conint_frontend:blue ./frontend_blue

build_green:
  stage: build
  tags:
    - build
  needs:
    - sonarqube-check
    - snyk-check  
  script:
    - echo "build green"
    - docker build -t cooopeir/conint_frontend:green ./frontend_green


test_backend:
  stage: test
  tags:
    - test
  script:
    - echo "Running tests on Vue.js frontend..."
    - cd frontend_blue  # Change directory to your Vue.js project
    - npm install  # Or 'yarn install' if you're using yarn
    - npm run lint  # Run linter
    - npm run test:unit  # Run unit tests
    - npm run test:e2e  # Run end-to-end tests
test_green:
  stage: test
  tags:
    - test
  script:
    - echo "Running tests on green..."
  #   # Add your test commands here

test_blue:
  stage: test
  tags:
    - test
  script:
    - echo "Running tests on blue..."
  #   # Add your test commands here

deliver_backend:
  stage: deliver
  tags:
    - deliver
  needs:
    - test_backend
  script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker push cooopeir/conint:latest
    - echo "Delivering backend to staging/production"
  #   # Add deployment steps here (e.g., SSH into EC2, pull and restart containers for green)

deliver_blue:
  stage: deliver
  tags:
    - deliver
  needs:
    - test_blue
  script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker push cooopeir/conint_frontend:blue
    - echo "Delivering Blue to staging/production"
  #   # Add deployment steps here (e.g., SSH into EC2, pull and restart containers for blue)

deliver_green:
  stage: deliver
  tags:
    - deliver
  needs:
    - test_green
  script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker push cooopeir/conint_frontend:green
    - echo "Delivering Green to staging/production"
  #   # Add deployment steps here (e.g., SSH into EC2, pull and restart containers for green)

deploy_backend:
  stage: deploy
  tags:
    - deploy
  script:
    - echo "Deploying Backend to staging/production"

deploy_blue:
  stage: deploy
  tags:
    - deploy
  script:
    - echo "Deploying Blue to staging/production"
    # Add deployment steps here (e.g., SSH into EC2, pull and restart containers)

deploy_green:
  stage: deploy
  tags:
    - deploy
  script:
    - echo "Deploying Green to staging/production"
    # Add deployment steps here (e.g., SSH into EC2, pull and restart containers)

update_nginx:
  stage: deploy
  tags:
    - deploy
  script:
    - echo "Updating nginx configuration..."
    - scp -i /path/to/your/private/key $NGINX_CONFIG_PATH ec2-user@blue_instance_ip:/tmp/nginx.conf
    - ssh -i /path/to/your/private/key ec2-user@blue_instance_ip sudo mv /tmp/nginx.conf $NGINX_CONFIG_PATH
    - ssh -i /path/to/your/private/key ec2-user@blue_instance_ip sudo systemctl reload nginx
    - echo "Nginx configuration updated for blue instance"

    - scp -i /path/to/your/private/key $NGINX_CONFIG_PATH ec2-user@green_instance_ip:/tmp/nginx.conf
    - ssh -i /path/to/your/private/key ec2-user@green_instance_ip sudo mv /tmp/nginx.conf $NGINX_CONFIG_PATH
    - ssh -i /path/to/your/private/key ec2-user@green_instance_ip sudo systemctl reload nginx
    - echo "Nginx configuration updated for green instance"
