# New version using our AWS RDS Instance instead of mariaedb volume

version: '3.8'

services:
  frontend_green:
    image: cooopeir/conint_frontend:green
    build:
      context: ./frontend_green
      dockerfile: Dockerfile
    container_name: frontend_green
    environment:
      - VITE_PORT=5174 # use different ports on the local machine
      - MESSAGE=Hello from Green # Hello from Blue

    restart: always
    depends_on:
      - backend
    ports:
      - "5174:5174"
    networks:
      - backend_frontend
    

  frontend_blue:
    image: cooopeir/conint_frontend:blue
    build:
      context: ./frontend_blue
      dockerfile: Dockerfile
    container_name: frontend_blue
    environment:
      - VITE_PORT=5173 # use different ports on the local machine
      - MESSAGE=Hello from Blue # Hello from Blue
    restart: always
    depends_on:
      - backend
    ports:
      - "5173:5173"
    networks:
      - backend_frontend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    environment:
      - "DB_DIALECT=mariadb"
      - "DB_USER=todo_admin"
      - "DB_PW=admin-pw"
      - "DB_HOST=mariadb-prod.c1gwkiqyc9gp.us-east-1.rds.amazonaws.com"
      - "DB_NAME=tododot"
    env_file: 
      - ./backend/env.local
    ports:
      - "8080:8080"
    networks:
      - backend_frontend

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend_green
      - frontend_blue
    networks:
      - backend_frontend

networks:
  backend_frontend:




# # Specify services that will interact
# services:

#   frontend_green:
#     image: cooopeir/conint_frontend:0.1

#     build:
#       context: ./frontend_green
#       dockerfile: Dockerfile

#     container_name: frontend_green
#     environment:
#       - VITE_PORT=5174 # use different ports on the local machine
#       - MESSAGE=Hello from Green # Hello from Blue

#     restart: always

#     depends_on:
#       - backend
#       - mariadb

#     ports:      
#       - "5174:5174"
#     networks:
#       - backend_mariadb

#   frontend_blue:
#     image: cooopeir/conint_frontend:0.2

#     build:
#       context: ./frontend_blue
#       dockerfile: Dockerfile

#     container_name: frontend_blue
#     environment:
#       - VITE_PORT=5173 # use different ports on the local machine
#       - MESSAGE=Hello from Blue # Hello from Blue

#     restart: always

#     depends_on:
#       - backend
#       - mariadb

#     ports:
#       - "5173:5173"
#     networks:
#       - backend_mariadb

#   mariadb:

#     build:
#       context: ./mariadb
#       dockerfile: Dockerfile

#     environment:
#       MYSQL_ROOT_PASSWORD: my-secret-pw
#       MYSQL_USER: todo-admin
#       MYSQL_PASSWORD: admin-pw
#       MYSQL_DATABASE: tododot
    
#     ports:
#       - "3306:3306"
    
#     restart: always
    
#     volumes:
#       - mariadb_volume_v2:/var/lib/mysql

#     networks:
#       - backend_mariadb

#   backend:
#     build:
#       context: ./backend
#       dockerfile: Dockerfile

#     depends_on:
#       - mariadb

#     restart: always

#     environment:
#       - "DB_DIALECT=mariadb"
#       - "DB_USER=todo-admin"
#       - "DB_PW=admin-pw"
#       - "DB_HOST=mariadb"
#       - "DB_NAME=tododot"

#     env_file: 
#       - ./backend/env.local

#     ports:
#       - "8080:8080"
    
#     networks:
#       - backend_mariadb      
#   nginx:
#     image: nginx:latest
#     container_name: nginx
#     ports:
#       - "80:80"
#     volumes:
#       - ./nginx.conf:/etc/nginx/nginx.conf
#     depends_on:
#       - backend
#       - mariadb
#       - frontend_green
#       - frontend_blue
      
#     networks:
#       - backend_mariadb
# networks:
#   backend_mariadb:

# volumes:
#   mariadb_volume_v2: 
