version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: npm Test Backend
          command: |
            cd backend  # Navigate to the directory with package.json
            npm install
            npm test
            cd ..
  
  sonarqube-check:
    docker:
      - image: sonarsource/sonar-scanner-cli
    steps:
      - checkout
      - run:
          name: Run SonarQube Scanner
          command: |
            sonar-scanner \
            -Dsonar.projectKey=CONINT-SonarQube \
            -Dsonar.sources=. \
            -Dsonar.exclusions=frontend_blue/tests/unit/Todo.test.js,frontend_blue/src/components/Todo.vue \
            -Dsonar.host.url=$SONAR_HOST_URL \
            -Dsonar.login=$SONAR_TOKEN
  
  build_test_deliver_backend:
    working_directory: ~/backend
    docker:
      - image: cimg/base:2022.09
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build backend Docker image
          command: |
            TAG=latest
            docker build -t $DOCKER_USERNAME/conint:$TAG .
      - run:
          name: Test backend
          command: |
            docker system prune -f
            npm install
            npm test
      - run:
          name: Deliver backend
          command: |
            TAG=latest
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
            docker push $DOCKER_USERNAME/conint:$TAG


workflows:
  version: 2
  build-and-deliver:
    jobs:
      - build
      - sonarqube-check
      - build_test_deliver_backend:
          requires:
            - sonarqube-check