version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests
          command: npm test

  sonarqube-check:
    docker:
      - image: sonarsource/sonar-scanner-cli:latest
    steps:
      - checkout
      - run:
          name: Run SonarQube Scanner
          command: |
            sonar-scanner \
              -Dsonar.projectKey=YOUR_PROJECT_KEY \
              -Dsonar.sources=src \
              -Dsonar.host.url=http://your-sonarqube-instance \
              -Dsonar.login=$SONAR_TOKEN

workflows:
  version: 2
  build-and-analyze:
    jobs:
      - build
      - sonarqube-check
