version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: npm Test Backend
          command: |
            cd backend  # Navigate to the directory with package.json
            npm install
            npm test
            cd ..

  sonarqube-check:
    docker:
      - image: sonarsource/sonar-scanner-cli:latest
    steps:
      - checkout
      - run:
        name: Run SonarQube Scanner
        command: sonar-scanner \
          -Dsonar.projectSettings=sonar-project.properties \
          -Dsonar.host.url=$SONAR_HOST_URL \
          -Dsonar.login=$SONAR_TOKEN

workflows:
  version: 2
  build-and-analyze:
    jobs:
      - build
      - sonarqube-check
